/**
 * Fork and PR — forks MaTriXy/Skillachi, patches leaderboard.json, opens a PR.
 */
import { spawnSync, execSync } from 'child_process';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { mkdtempSync, rmSync } from 'fs';
import { tmpdir } from 'os';
import path from 'path';

const REPO = 'MaTriXy/Skillachi';

function gh(args, opts = {}) {
  const result = spawnSync('gh', args, { encoding: 'utf8', timeout: 60_000, ...opts });
  if (result.error) throw result.error;
  return result.stdout?.trim() || '';
}

export async function forkAndPR({ benchmarkId, skillId, skillName, roleId, scoreResult, diffs }) {
  try {
    // 1. Fork (idempotent)
    console.log('  Forking MaTriXy/Skillachi...');
    gh(['repo', 'fork', REPO, '--clone=false']);

    // 2. Get username
    const username = gh(['api', 'user', '--jq', '.login']);
    if (!username) throw new Error('Could not get GitHub username. Run: gh auth login');

    // 3. Clone fork
    const forkDir = mkdtempSync(path.join(tmpdir(), 'skillachi-pr-'));
    const forkUrl = `https://github.com/${username}/Skillachi.git`;
    execSync(`git clone --depth 1 "${forkUrl}" "${forkDir}"`, { stdio: 'pipe', timeout: 120_000 });

    // 4. Patch leaderboard.json
    const lbPath = path.join(forkDir, 'benchmarks', 'leaderboard.json');
    const scaffoldPath = path.join(forkDir, 'benchmarks', 'leaderboard-scaffold.json');
    let lb = [];
    if (existsSync(lbPath)) {
      try { lb = JSON.parse(readFileSync(lbPath, 'utf8')); } catch {}
    }
    if (!lb.length && existsSync(scaffoldPath)) {
      lb = JSON.parse(readFileSync(scaffoldPath, 'utf8'));
    }

    const idx = lb.findIndex(s => s.benchmarkId === benchmarkId && s.skillId === skillId);
    const entry = idx >= 0 ? lb[idx] : { benchmarkId, skillId, skillName, roleId };
    entry.score = scoreResult.average?.overall ?? null;
    entry.scoreDetail = { ...scoreResult, diff: (diffs?.claude || '').slice(0, 8000) };
    entry.runAt = new Date().toISOString();
    if (idx >= 0) lb[idx] = entry; else lb.push(entry);
    writeFileSync(lbPath, JSON.stringify(lb, null, 2));

    // 5. Commit and push
    const branchName = `score/${benchmarkId.slice(0, 40)}-${skillId.slice(0, 20)}`.replace(/[^a-z0-9-]/gi, '-');
    execSync(`git -C "${forkDir}" checkout -b "${branchName}"`, { stdio: 'pipe' });
    execSync(`git -C "${forkDir}" config user.email "skillachi-runner@users.noreply.github.com"`, { stdio: 'pipe' });
    execSync(`git -C "${forkDir}" config user.name "skillachi-runner"`, { stdio: 'pipe' });
    execSync(`git -C "${forkDir}" add benchmarks/leaderboard.json`, { stdio: 'pipe' });
    execSync(`git -C "${forkDir}" commit -m "feat: score ${skillName} x ${roleId} (avg ${scoreResult.average?.overall ?? '?'})"`, { stdio: 'pipe' });
    execSync(`git -C "${forkDir}" push origin "${branchName}"`, { stdio: 'pipe', timeout: 60_000 });

    // 6. Open PR
    const avgScore = scoreResult.average?.overall?.toFixed(2) ?? '?';
    const body = [
      `## Skillachi Benchmark Result`,
      ``,
      `**Skill:** ${skillName}`,
      `**Role:** ${roleId}`,
      `**Benchmark:** ${benchmarkId}`,
      ``,
      `| Model | Score |`,
      `|-------|-------|`,
      `| Claude | ${scoreResult.claude?.overall ?? '—'} |`,
      `| Codex | ${scoreResult.codex?.overall ?? '—'} |`,
      `| Gemini | ${scoreResult.gemini?.overall ?? '—'} |`,
      `| **Average** | **${avgScore}** |`,
      ``,
      `*Generated by [skillachi-runner](https://github.com/MaTriXy/Skillachi)*`,
    ].join('\n');

    const prUrl = gh([
      'pr', 'create',
      '--repo', REPO,
      '--head', `${username}:${branchName}`,
      '--title', `feat: score ${skillName} x ${roleId} (avg ${avgScore})`,
      '--body', body,
    ]);

    // 7. Cleanup fork clone
    try { rmSync(forkDir, { recursive: true, force: true }); } catch {}

    return { prUrl, success: true };
  } catch (e) {
    console.error(`  PR failed: ${e.message}`);
    return { prUrl: null, success: false };
  }
}
